[package]
name = "example-shadow-mode"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
reflex-core = { workspace = true }
reflex-provider = { workspace = true }
reflex-policy = { workspace = true }
reflex-telemetry = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
